version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ./data:/root/.ollama
    ports:
      - "11434:11434"

  ollama-ui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-ui
    restart: unless-stopped
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    volumes:
      - ./ui:/app/data